#phamjk .bash_profile

# Set Term Colors
export TERM=xterm-256color

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
PATH=$PATH:$HOME/bin:$HOME/.local/bin
export PATH

# User specific aliases and functions
source ~/.alias

